export enum ApiErrorCode {
  StatusCodeSuccess = 0,
  StatusCodeFailed = 1,
  StatusCodeInternalError = 2,
  StatusCodeForbiden = 3,
  StatusCodeUnauthorized = 4,
  StatusCodeValidationFailed = 5,
  StatusCodeBadRequest = 6,

  // User
  StatusCodeUserUsernameRequired = 1000,
  StatusCodeUserUsernameTooShort = 1001,
  StatusCodeUserUsernameTooLong = 1002,
  StatusCodeUserUsernameAlreadyExist = 1003,
  StatusCodeUserEmailRequired = 1004,
  StatusCodeUserEmailTooShort = 1005,
  StatusCodeUserEmailTooLong = 1006,
  StatusCodeUserEmailAlreadyExist = 1007,
  StatusCodeUserPasswordRequired = 1008,
  StatusCodeUserPasswordTooShort = 1009,
  StatusCodeUserPasswordTooLong = 1010,
  StatusCodeUserFirstNameTooShort = 1011,
  StatusCodeUserFirstNameTooLong = 1012,
  StatusCodeUserFirstNameRequired = 1013,
  StatusCodeUserLastNameTooShort = 1014,
  StatusCodeUserLastNameTooLong = 1015,
  StatusCodeUserLastNameRequired = 1016,
  StatusCodeUserPhoneTooLong = 1017,
  StatusCodeUserNotFound = 1018,

  StatusCodeRoleNameRequired = 1100,
  StatusCodeRoleNameTooLong = 1101,
  StatusCodeRoleNameAlreadyExist = 1102,
  StatusCodeRoleDescriptionTooLong = 1103,
  StatusCodeRoleNotFound = 1104,
  // Auth
  StatusCodeLoginUsernameOrPasswordIncorrect = 1500,
}
