export type GetCompanyResponse = {
  id: string;
  name: string;
  legalName: string;
  registrationNumber: string;
  taxId: string;
  website: string;
  email: string;
  phone: string;
  logoUrl: string;
  address: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
  currencyCode: string;
  timezone: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
};
